# Generated by Django 5.1 on 2024-09-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='image/')),
                ('upload_to', models.DateTimeField(auto_now_add=True)),
                ('h4', models.CharField(max_length=555)),
                ('p', models.CharField(max_length=555)),
                ('link', models.CharField(max_length=555)),
            ],
        ),
    ]
